---
agriculture_final_demand_bio_kerosene:
  demand: 0.0
agriculture_final_demand_biodiesel:
  demand: 0.0
agriculture_final_demand_crude_oil:
  input:
    :diesel: 0.0
    :biodiesel: 0.0
    :kerosene: 0.0
    :bio_kerosene: 0.0
    :lpg: 0.0
    :bio_oil: 0.0
    :crude_oil: 1.0
agriculture_final_demand_diesel:
  demand: 0.0
agriculture_final_demand_electricity:
  demand: 0.0
agriculture_final_demand_kerosene:
  demand: 0.0
agriculture_final_demand_lpg:
  demand: 0.0
agriculture_final_demand_network_gas:
  demand: 0.0
agriculture_final_demand_other_bio_oil:
  demand: 0.0
agriculture_final_demand_other_oil:
  demand: 0.0
agriculture_final_demand_steam_hot_water:
  demand: 0.0
agriculture_final_demand_wood_pellets:
  demand: 0.0
buildings_final_demand_bio_kerosene:
  demand: 0.0
buildings_final_demand_biodiesel:
  demand: 0.0
buildings_final_demand_coal:
  demand: 0.0
buildings_final_demand_crude_oil:
  input: &1
    :diesel: 0.0
    :biodiesel: 0.0
    :kerosene: 0.0
    :bio_kerosene: 0.0
    :lpg: 0.0
    :bio_oil: 0.0
    :crude_oil: 1.0
buildings_final_demand_diesel:
  demand: 0.0
buildings_final_demand_kerosene:
  demand: 0.0
buildings_final_demand_lpg:
  demand: 0.0
buildings_final_demand_network_gas:
  demand: 0.0
buildings_final_demand_other_bio_oil:
  demand: 0.0
buildings_final_demand_other_oil:
  demand: 0.0
buildings_final_demand_solar_thermal:
  demand: 0.0
buildings_final_demand_steam_hot_water:
  demand: 0.0
buildings_final_demand_wood_pellets:
  demand: 0.0
buildings_local_production_electricity:
  demand: 0.0
buildings_solar_pv_solar_radiation:
  demand: 0.0
energy_chp_combined_cycle_network_gas:
  demand: 0.0
energy_chp_local_engine_biogas:
  demand: 0.0
energy_chp_local_engine_network_gas:
  demand: 0.0
energy_chp_local_wood_pellets:
  demand: 0.0
energy_chp_supercritical_waste_mix:
  demand: 0.0
energy_chp_ultra_supercritical_coal:
  demand: 0.0
energy_chp_ultra_supercritical_cofiring_coal:
  demand: 0.0
energy_extraction_coal:
  demand: 0.0
energy_extraction_crude_oil:
  demand: 0.0
energy_extraction_lignite:
  demand: 0.0
energy_extraction_natural_gas:
  demand: 0.0
energy_extraction_uranium_oxide:
  demand: 0.0
energy_heat_burner_coal:
  demand: 0.0
energy_heat_burner_crude_oil:
  demand: 0.0
energy_heat_burner_hydrogen:
  demand: 0.0
energy_heat_burner_network_gas:
  demand: 0.0
energy_heat_burner_waste_mix:
  demand: 0.0
energy_heat_burner_wood_pellets:
  demand: 0.0
energy_heat_distribution_loss:
  demand: 0.0
energy_heat_heatpump_water_water_electricity:
  demand: 0.0
energy_heat_solar_thermal:
  demand: 0.0
energy_heat_well_geothermal:
  demand: 0.0
energy_power_combined_cycle_ccs_coal:
  demand: 0.0
energy_power_combined_cycle_ccs_network_gas:
  demand: 0.0
energy_power_combined_cycle_coal:
  demand: 0.0
energy_power_combined_cycle_network_gas:
  demand: 24.13886987
energy_power_engine_diesel:
  demand: 0.0
energy_power_engine_network_gas:
  demand: 0.0
energy_power_geothermal:
  demand: 0.0
energy_power_hv_network_loss:
  demand: 1.658837664
energy_power_hydro_river:
  demand: 0.0
energy_power_nuclear_gen2_uranium_oxide:
  demand: 3.632634563
energy_power_sector_own_use_electricity:
  demand: 0.0
energy_power_solar_pv_solar_radiation:
  demand: 0.0
energy_power_supercritical_coal:
  demand: 0.0
energy_power_supercritical_waste_mix:
  demand: 0.0
energy_power_turbine_network_gas:
  demand: 0.0
energy_power_ultra_supercritical_coal:
  demand: 21.8555687
energy_power_ultra_supercritical_cofiring_coal:
  demand: 6.732295714
energy_power_ultra_supercritical_crude_oil:
  demand: 0.0
energy_power_ultra_supercritical_network_gas:
  demand: 0.0
energy_power_wind_turbine_coastal:
  demand: 0.0
energy_power_wind_turbine_inland:
  demand: 1.899617873
energy_power_wind_turbine_offshore:
  demand: 0.335226684
households_final_demand_bio_kerosene:
  demand: 0.0
households_final_demand_biodiesel:
  demand: 0.0
households_final_demand_coal:
  demand: 0.0
households_final_demand_crude_oil:
  input: *1
households_final_demand_diesel:
  demand: 0.0
households_final_demand_electricity:
  demand: 29.6957826001583
households_final_demand_kerosene:
  demand: 0.0
households_final_demand_lpg:
  demand: 0.0
households_final_demand_network_gas:
  demand: 133.948497
households_final_demand_other_bio_oil:
  demand: 0.0
households_final_demand_other_oil:
  demand: 0.0
households_final_demand_steam_hot_water:
  demand: 0.0
households_final_demand_wood_pellets:
  demand: 1.37331749802059
households_solar_pv_solar_radiation:
  demand: 4.25114470681384
industry_chp_combined_cycle_gas_power_fuelmix:
  demand: 0.0
industry_chp_engine_gas_power_fuelmix:
  demand: 0.0
industry_chp_turbine_gas_power_fuelmix:
  demand: 0.0
industry_chp_ultra_supercritical_coal:
  demand: 0.0
industry_chp_wood_pellets:
  demand: 0.0
industry_final_demand_bio_kerosene:
  demand: 0.0
industry_final_demand_biodiesel:
  demand: 0.0
industry_final_demand_coal:
  demand: 0.0
industry_final_demand_coal_gas:
  demand: 0.0
industry_final_demand_coal_non_energetic:
  demand: 0.0
industry_final_demand_cokes:
  demand: 0.0
industry_final_demand_crude_oil:
  input: *1
industry_final_demand_diesel:
  demand: 0.0
industry_final_demand_electricity:
  demand: 0.0
industry_final_demand_for_chemical_other_crude_oil_non_energetic:
  demand: 0.0
industry_final_demand_for_other_crude_oil_non_energetic:
  demand: 0.0
industry_final_demand_kerosene:
  demand: 0.0
industry_final_demand_lpg:
  demand: 0.0
industry_final_demand_network_gas:
  demand: 0.0
industry_final_demand_network_gas_non_energetic:
  demand: 0.0
industry_final_demand_other_bio_oil:
  demand: 0.0
industry_final_demand_other_oil:
  demand: 0.0
industry_final_demand_steam_hot_water:
  demand: 0.0
industry_final_demand_wood_pellets:
  demand: 0.0
industry_final_demand_wood_pellets_non_energetic:
  demand: 0.0
industry_heat_burner_coal:
  demand: 0.0
industry_heat_burner_crude_oil:
  demand: 0.0
industry_heat_burner_lignite:
  demand: 0.0
industry_heat_well_geothermal:
  demand: 0.0
industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic:
  demand: 0.0
other_final_demand_coal:
  demand: 0.0
other_final_demand_crude_oil:
  demand: 0.0
other_final_demand_crude_oil_non_energetic:
  demand: 0.0
other_final_demand_electricity:
  demand: 0.0
other_final_demand_network_gas:
  demand: 0.0
other_final_demand_steam_hot_water:
  demand: 0.0
other_final_demand_wood_pellets:
  demand: 0.0
transport_final_demand_bio_ethanol:
  demand: 0.0
transport_final_demand_bio_lng:
  demand: 0.0
transport_final_demand_biodiesel:
  demand: 0.0
transport_final_demand_coal:
  demand: 0.0
transport_final_demand_compressed_network_gas:
  demand: 0.0
transport_final_demand_crude_oil_non_energetic:
  demand: 0.0
transport_final_demand_diesel:
  demand: 0.0
transport_final_demand_electricity:
  demand: 0.0
transport_final_demand_for_road_bio_lng:
  demand: 0.0
transport_final_demand_for_road_compressed_network_gas:
  demand: 0.0
transport_final_demand_for_road_lng:
  demand: 0.0
transport_final_demand_for_shipping_bio_lng:
  demand: 0.0
transport_final_demand_for_shipping_lng:
  demand: 0.0
transport_final_demand_gasoline:
  demand: 0.0
transport_final_demand_heavy_fuel_oil:
  demand: 0.0
transport_final_demand_kerosene:
  demand: 0.0
transport_final_demand_lng:
  demand: 0.0
transport_final_demand_lpg:
  demand: 0.0
transport_rail_mixer_diesel:
  input:
    diesel: 1.0
    biodiesel: 0.0
transport_road_mixer_diesel:
  input:
    diesel: 1.0
    biodiesel: 0.0
transport_road_mixer_gasoline:
  input:
    gasoline: 1.0
    bio_ethanol: 0.0
transport_useful_demand_bicycles:
  demand: 6.92591128882276
transport_useful_demand_cars:
  number_of_units: 2565.0
agriculture_final_demand_electricity-agriculture_geothermal@electricity:
  parent_share: 0.0
agriculture_final_demand_electricity-agriculture_heatpump_water_water_ts_electricity@electricity:
  parent_share: 0.0
buildings_final_demand_for_cooling_electricity-buildings_cooling_heatpump_air_water_electricity@electricity:
  parent_share: 0.0
buildings_final_demand_for_space_heating_electricity-buildings_space_heater_heatpump_air_water_electricity@electricity:
  parent_share: 0.0
buildings_local_production_electricity-buildings_final_demand_electricity@electricity:
  parent_share: 1.0
buildings_local_production_electricity-industry_final_demand_for_other_ict_dsr_electricity@electricity:
  parent_share: 0.0
households_final_demand_for_hot_water_electricity-households_water_heater_heatpump_air_water_electricity@electricity:
  parent_share: 0.0133
households_final_demand_for_hot_water_electricity-households_water_heater_hybrid_heatpump_air_water_electricity@electricity:
  parent_share: 0.0
households_final_demand_for_hot_water_network_gas-households_water_heater_combined_network_gas@network_gas:
  parent_share: 0.9581
households_final_demand_for_hot_water_network_gas-households_water_heater_hybrid_heatpump_air_water_electricity@network_gas:
  parent_share: 0.0
households_final_demand_for_space_heating_electricity-households_space_heater_electricity@electricity:
  parent_share: 0.9124
households_final_demand_for_space_heating_electricity-households_space_heater_heatpump_air_water_electricity@electricity:
  parent_share: 0.0425
households_final_demand_for_space_heating_electricity-households_space_heater_hybrid_heatpump_air_water_electricity@electricity:
  parent_share: 0.0
households_final_demand_for_space_heating_network_gas-households_space_heater_combined_network_gas@network_gas:
  parent_share: 0.9581
households_final_demand_for_space_heating_network_gas-households_space_heater_hybrid_heatpump_air_water_electricity@network_gas:
  parent_share: 0.0
households_final_demand_for_space_heating_network_gas-households_space_heater_network_gas@network_gas:
  parent_share: 0.0419
industry_final_demand_coal-industry_final_demand_for_chemical_coal@coal:
  parent_share: 0.0
industry_final_demand_coal-industry_final_demand_for_metal_coal@coal:
  parent_share: 0.0
industry_final_demand_coal_non_energetic-industry_final_demand_for_chemical_coal_non_energetic@coal:
  parent_share: 0.0
industry_final_demand_crude_oil-industry_final_demand_for_chemical_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_crude_oil-industry_final_demand_for_metal_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_crude_oil-industry_final_demand_for_other_crude_oil@crude_oil:
  parent_share: 1.0
industry_final_demand_crude_oil_non_energetic-industry_final_demand_for_chemical_crude_oil_non_energetic@crude_oil:
  parent_share: 0.0
industry_final_demand_crude_oil_non_energetic-industry_final_demand_for_other_crude_oil_non_energetic@crude_oil:
  parent_share: 1.0
industry_final_demand_electricity-industry_final_demand_for_chemical_dsr_electricity@electricity:
  parent_share: 0.0
industry_final_demand_electricity-industry_final_demand_for_metal_dsr_electricity@electricity:
  parent_share: 0.0
industry_final_demand_electricity-industry_final_demand_for_other_dsr_electricity@electricity:
  parent_share: 1.0
industry_final_demand_for_chemical_coal-industry_final_demand_for_chemical_fertilizers_coal@coal:
  parent_share: 0.0
industry_final_demand_for_chemical_coal-industry_final_demand_for_chemical_other_coal@coal:
  parent_share: 1.0
industry_final_demand_for_chemical_coal-industry_final_demand_for_chemical_refineries_coal@coal:
  parent_share: 0.0
industry_final_demand_for_chemical_coal_non_energetic-industry_final_demand_for_chemical_other_coal_non_energetic@coal:
  parent_share: 1.0
industry_final_demand_for_chemical_coal_non_energetic-industry_final_demand_for_chemical_refineries_coal_non_energetic@coal:
  parent_share: 0.0
industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_fertilizers_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_other_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_refineries_crude_oil@crude_oil:
  parent_share: 0.0
? industry_final_demand_for_chemical_crude_oil_non_energetic-industry_final_demand_for_chemical_fertilizers_crude_oil_non_energetic@crude_oil
: parent_share: 0.0
industry_final_demand_for_chemical_electricity-industry_final_demand_for_chemical_fertilizers_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_chemical_electricity-industry_final_demand_for_chemical_other_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_chemical_electricity-industry_final_demand_for_chemical_refineries_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_chemical_network_gas-industry_final_demand_for_chemical_fertilizers_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_chemical_network_gas-industry_final_demand_for_chemical_other_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_chemical_network_gas-industry_final_demand_for_chemical_refineries_network_gas@network_gas:
  parent_share: 0.0
? industry_final_demand_for_chemical_network_gas_non_energetic-industry_final_demand_for_chemical_fertilizers_network_gas_non_energetic@network_gas
: parent_share: 0.0
? industry_final_demand_for_chemical_network_gas_non_energetic-industry_final_demand_for_chemical_other_network_gas_non_energetic@network_gas
: parent_share: 0.0
? industry_final_demand_for_chemical_network_gas_non_energetic-industry_final_demand_for_chemical_refineries_network_gas_non_energetic@network_gas
: parent_share: 0.0
? industry_final_demand_for_chemical_steam_hot_water-industry_final_demand_for_chemical_fertilizers_steam_hot_water@steam_hot_water
: parent_share: 0.0
industry_final_demand_for_chemical_steam_hot_water-industry_final_demand_for_chemical_other_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_chemical_steam_hot_water-industry_final_demand_for_chemical_refineries_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_chemical_wood_pellets-industry_final_demand_for_chemical_fertilizers_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_for_chemical_wood_pellets-industry_final_demand_for_chemical_other_wood_pellets@wood_pellets:
  parent_share: 1.0
industry_final_demand_for_chemical_wood_pellets-industry_final_demand_for_chemical_refineries_wood_pellets@wood_pellets:
  parent_share: 0.0
? industry_final_demand_for_chemical_wood_pellets_non_energetic-industry_final_demand_for_chemical_fertilizers_wood_pellets_non_energetic@wood_pellets
: parent_share: 0.0
? industry_final_demand_for_chemical_wood_pellets_non_energetic-industry_final_demand_for_chemical_other_wood_pellets_non_energetic@wood_pellets
: parent_share: 1.0
? industry_final_demand_for_chemical_wood_pellets_non_energetic-industry_final_demand_for_chemical_refineries_wood_pellets_non_energetic@wood_pellets
: parent_share: 0.0
industry_final_demand_for_metal_coal-industry_final_demand_for_metal_steel_coal@coal:
  parent_share: 0.0
industry_final_demand_for_metal_crude_oil-industry_final_demand_for_metal_steel_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_final_demand_for_metal_aluminium_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_final_demand_for_metal_steel_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_network_gas-industry_final_demand_for_metal_aluminium_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_metal_network_gas-industry_final_demand_for_metal_steel_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_metal_steam_hot_water-industry_final_demand_for_metal_steel_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_other_coal-industry_final_demand_for_other_food_coal@coal:
  parent_share: 0.0
industry_final_demand_for_other_coal-industry_final_demand_for_other_paper_coal@coal:
  parent_share: 0.0
industry_final_demand_for_other_crude_oil-industry_final_demand_for_other_food_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_other_crude_oil-industry_final_demand_for_other_paper_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_other_electricity-industry_final_demand_for_other_food_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_other_electricity-industry_final_demand_for_other_paper_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_other_network_gas-industry_final_demand_for_other_food_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_other_network_gas-industry_final_demand_for_other_paper_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_other_steam_hot_water-industry_final_demand_for_other_food_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_other_steam_hot_water-industry_final_demand_for_other_paper_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_other_wood_pellets-industry_final_demand_for_other_food_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_for_other_wood_pellets-industry_final_demand_for_other_paper_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_network_gas-industry_final_demand_for_chemical_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_network_gas-industry_final_demand_for_metal_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_steam_hot_water-industry_final_demand_for_chemical_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_steam_hot_water-industry_final_demand_for_metal_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_wood_pellets-industry_final_demand_for_chemical_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_wood_pellets-industry_final_demand_for_metal_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_wood_pellets_non_energetic-industry_final_demand_for_chemical_wood_pellets_non_energetic@wood_pellets:
  parent_share: 0.0
transport_final_demand_diesel-transport_final_demand_for_rail_diesel@diesel:
  parent_share: 0.0
transport_final_demand_diesel-transport_final_demand_for_road_diesel@diesel:
  parent_share: 1.0
transport_final_demand_for_rail_electricity-transport_tram_using_electricity@electricity:
  parent_share: 0.0
transport_final_demand_gasoline-transport_final_demand_for_road_gasoline@gasoline:
  parent_share: 1.0
