# Configuration for a simple CSV file which contains residual loads based on queries.
# Each curve is output in a column, with each row containing a value for the hour.
---
- name: Total integral costs of produced hydrogen (Eur/MWh)
  query: total_hydrogen_production_cost_curve_per_mwh

- name: Total production of Hydrogen (MWh)
  query: hydrogen_production_curve

- name: Production curve ammonia reformer (dispatchable) (MWh)
  query: energy_hydrogen_ammonia_reformer_dispatchable_hydrogen_output_curve

- name: Production cost curve ammonia reformer (dispatchable) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_ammonia_reformer_dispatchable

- name: Production curve ammonia reformer (must-run) (MWh)
  query: energy_hydrogen_ammonia_reformer_must_run_hydrogen_output_curve

- name: Production cost curve ammonia reformer (must-run) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_ammonia_reformer_must_run

- name: Production curve autothermal reformer (dispatchable) (MWh)
  query: energy_hydrogen_autothermal_reformer_dispatchable_hydrogen_output_curve

- name: Production cost curve autothermal reformer (dispatchable) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_autothermal_reformer_dispatchable

- name: Production curve autothermal reformer (must-run) (MWh)
  query: energy_hydrogen_autothermal_reformer_must_run_hydrogen_output_curve

- name: Production cost curve autothermal reformer (must-run) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_autothermal_reformer_must_run

- name: Production curve autothermal reformer (CCS must-run) (MWh) 
  query: energy_hydrogen_autothermal_reformer_ccs_must_run_hydrogen_output_curve

- name: Production cost curve autothermal reformer (CCS must-run) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_autothermal_reformer_ccs_must_run

- name: Production curve biomass gasification (MWh)
  query: energy_hydrogen_biomass_gasification_hydrogen_output_curve

- name: Production cost curve biomass gasification (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_biomass_gasification

- name: Production curve biomass gasification (CCS) (MWh)
  query: energy_hydrogen_biomass_gasification_ccs_hydrogen_output_curve

- name: Production cost curve biomass gasification (CCS) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_biomass_gasification_ccs

- name: Production curve solar electrolysis (MWh)
  query: energy_hydrogen_electrolysis_solar_electricity_hydrogen_output_curve

- name: Production cost curve solar electrolysis (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_solar_pv

- name: Production curve wind electrolysis (MWh)
  query: energy_hydrogen_electrolysis_wind_electricity_hydrogen_output_curve

- name: Production cost curve wind electrolysis (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_offshore_wind_turbine

- name: Production curve hybrid offshore electrolyser (MWh)
  query: energy_hydrogen_hybrid_electrolysis_wind_electricity_hydrogen_output_curve

- name: Production cost curve hybrid offshore electrolyser (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_hybrid_offshore_wind_turbine

- name: Production curve power to gas (MWh)
  query: energy_hydrogen_flexibility_p2g_electricity_hydrogen_output_curve

- name: Production cost curve power to gas (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_p2g

- name: Production curve liquid hydrogen regasifier (MWh)
  query: energy_hydrogen_liquid_hydrogen_regasifier_hydrogen_output_curve

- name: Production cost curve liquid hydrogen regasifier (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_liquid_hydrogen_regasifier

- name: Production curve LOHC reformer (MWh)
  query: energy_hydrogen_liquid_hydrogen_regasifier_hydrogen_output_curve

- name: Production cost curve liquid hydrogen regasifier (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_liquid_hydrogen_regasifier

- name: Production curve steam methane reformer (dispatchable) (MWh)
  query: energy_hydrogen_autothermal_reformer_dispatchable_hydrogen_output_curve

- name: Production cost curve steam methane reformer (dispatchable) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_steam_methane_reformer_dispatchable

- name: Production curve steam methane reformer (must-run) (MWh)
  query: energy_hydrogen_steam_methane_reformer_must_run_hydrogen_output_curve

- name: Production cost curve steam methane reformer (must-run) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_steam_methane_reformer_must_run

- name: Production curve steam methane reformer (CCS must-run) (MWh)
  query: energy_hydrogen_steam_methane_reformer_ccs_must_run_hydrogen_output_curve

- name: Production cost curve steam methane reformer (CCS must-run) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_steam_methane_reformer_ccs_must_run

- name: Production curve storage depleted gas fields (MWh)
  query: energy_hydrogen_storage_depleted_gas_field_hydrogen_output_curve

- name: Production cost curve storage depleted gas fields (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_storage_depleted_gas_field

- name: Production curve storage salt caverns (MWh)
  query: energy_hydrogen_storage_salt_cavern_hydrogen_output_curve

- name: Production cost curve storage salt caverns (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_storage_salt_cavern

- name: Production curve import (back-up) (MWh)
  query: energy_imported_hydrogen_backup_hydrogen_output_curve

- name: Production cost curve import (back-up) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_imported

- name: Production curve import (baseload) (MWh)
  query: energy_imported_hydrogen_baseload_hydrogen_output_curve

- name: Production cost curve import (baseload) (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_imported

- name: Production curve residual industrial hydrogen (MWh)
  query: industry_residual_hydrogen_hydrogen_output_curve

- name: Production cost curve residual industrial hydrogen (Eur/MWh)
  query: production_costs_per_mwh_curve_hydrogen_industry_residual_hydrogen


