---
energy_chp_supercritical_ccs_waste_mix_captured_co2:
  x: 2220
  y: 540
energy_chp_supercritical_ccs_waste_mix_co2:
  x: 2720
  y: 540
energy_chp_supercritical_ccs_waste_mix_emitted_co2:
  x: 2220
  y: 600
energy_cokesoven_consumption_coal_gas_co2:
  x: 3440
  y: 1120
energy_hydrogen_biomass_gasification_ccs_captured_co2:
  x: 2220
  y: 800
energy_hydrogen_biomass_gasification_ccs_co2:
  x: 2720
  y: 820
energy_hydrogen_biomass_gasification_ccs_emitted_co2:
  x: 2220
  y: 860
energy_hydrogen_captured_co2:
  x: 1940
  y: 720
energy_hydrogen_steam_methane_reformer_ccs_captured_co2:
  x: 2220
  y: 920
energy_hydrogen_steam_methane_reformer_ccs_co2:
  x: 2720
  y: 880
energy_hydrogen_steam_methane_reformer_ccs_emitted_co2:
  x: 2220
  y: 980
energy_power_captured_co2:
  x: 1940
  y: 200
energy_power_combined_cycle_ccs_coal_captured_co2:
  x: 2220
  y: 0
energy_power_combined_cycle_ccs_coal_co2:
  x: 2720
  y: 0
energy_power_combined_cycle_ccs_coal_emitted_co2:
  x: 2220
  y: 60
energy_power_combined_cycle_ccs_network_gas_captured_co2:
  x: 2220
  y: 140
energy_power_combined_cycle_ccs_network_gas_co2:
  x: 2720
  y: 140
energy_power_combined_cycle_ccs_network_gas_emitted_co2:
  x: 2220
  y: 200
energy_power_supercritical_ccs_waste_mix_captured_co2:
  x: 2220
  y: 660
energy_power_supercritical_ccs_waste_mix_co2:
  x: 2720
  y: 660
energy_power_supercritical_ccs_waste_mix_emitted_co2:
  x: 2220
  y: 720
energy_power_ultra_supercritical_ccs_coal_captured_co2:
  x: 2220
  y: 280
energy_power_ultra_supercritical_ccs_coal_co2:
  x: 2720
  y: 280
energy_power_ultra_supercritical_ccs_coal_emitted_co2:
  x: 2220
  y: 340
energy_power_ultra_supercritical_oxyfuel_ccs_lignite_captured_co2:
  x: 2220
  y: 420
energy_power_ultra_supercritical_oxyfuel_ccs_lignite_co2:
  x: 2720
  y: 420
energy_power_ultra_supercritical_oxyfuel_ccs_lignite_emitted_co2:
  x: 2220
  y: 480
energy_steel_hisarna_transformation_coal_co2:
  x: 3440
  y: 1200
industry_chemicals_fertilizers_capture_potential_combustion_co2:
  x: 2450
  y: 1780
industry_chemicals_fertilizers_capture_potential_processes_co2:
  x: 2450
  y: 2040
industry_chemicals_fertilizers_captured_co2:
  x: 1940
  y: 1840
industry_chemicals_fertilizers_captured_combustion_co2:
  x: 2230
  y: 1700
industry_chemicals_fertilizers_captured_processes_co2:
  x: 2240
  y: 1920
industry_chemicals_fertilizers_combustion_co2:
  x: 2950
  y: 1780
industry_chemicals_fertilizers_emitted_co2:
  x: 1940
  y: 2040
industry_chemicals_fertilizers_processes_co2:
  x: 2950
  y: 2060
industry_final_demand_for_chemical_fertilizers_coal_co2:
  x: 3450
  y: 1840
industry_final_demand_for_chemical_fertilizers_crude_oil_co2:
  x: 3450
  y: 1900
industry_final_demand_for_chemical_fertilizers_network_gas_co2:
  x: 3450
  y: 1780
industry_final_demand_for_chemical_fertilizers_network_gas_non_energetic_co2:
  x: 3450
  y: 2060
industry_final_demand_for_chemical_fertilizers_wood_pellets_co2:
  x: 3450
  y: 1960
industry_final_demand_for_other_food_coal_co2:
  x: 3450
  y: 2540
industry_final_demand_for_other_food_crude_oil_co2:
  x: 3450
  y: 2600
industry_final_demand_for_other_food_network_gas_co2:
  x: 3450
  y: 2660
industry_final_demand_for_other_food_wood_pellets_co2:
  x: 3450
  y: 2720
industry_final_demand_for_other_paper_coal_co2:
  x: 3450
  y: 2220
industry_final_demand_for_other_paper_crude_oil_co2:
  x: 3450
  y: 2280
industry_final_demand_for_other_paper_network_gas_co2:
  x: 3450
  y: 2340
industry_final_demand_for_other_paper_wood_pellets_co2:
  x: 3450
  y: 2400
industry_other_food_capture_potential_co2:
  x: 2450
  y: 2540
industry_other_food_captured_co2:
  x: 1940
  y: 2540
industry_other_food_combustion_co2:
  x: 2950
  y: 2540
industry_other_food_emitted_co2:
  x: 1940
  y: 2720
industry_other_paper_capture_potential_co2:
  x: 2450
  y: 2220
industry_other_paper_captured_co2:
  x: 1940
  y: 2220
industry_other_paper_combustion_co2:
  x: 2950
  y: 2220
industry_other_paper_emitted_co2:
  x: 1940
  y: 2400
industry_steel_blastfurnace_burner_coal_gas_co2:
  x: 3440
  y: 1060
industry_steel_blastfurnace_capture_potential_co2:
  x: 2440
  y: 1140
industry_steel_blastfurnace_captured_co2:
  x: 2220
  y: 1140
industry_steel_blastfurnace_co2:
  x: 2940
  y: 1120
industry_steel_captured_co2:
  x: 1940
  y: 1180
industry_steel_electricfurnace_burner_network_gas_co2:
  x: 3450
  y: 1540
industry_steel_electricfurnace_capture_potential_co2:
  x: 2450
  y: 1540
industry_steel_electricfurnace_captured_co2:
  x: 2220
  y: 1540
industry_steel_electricfurnace_co2:
  x: 2950
  y: 1540
industry_steel_emitted_co2:
  x: 1940
  y: 1380
industry_steel_hisarna_capture_potential_co2:
  x: 2440
  y: 1220
industry_steel_hisarna_captured_co2:
  x: 2220
  y: 1220
industry_steel_hisarna_co2:
  x: 2940
  y: 1200
molecules_direct_air_capture_co2:
  x: 1940
  y: 1020
molecules_distribution_after_transport_co2:
  x: 860
  y: 440
molecules_distribution_before_transport_co2:
  x: 1440
  y: 440
molecules_export_co2:
  x: 360
  y: 340
molecules_import_co2:
  x: 1940
  y: 1080
molecules_offshore_sequestration_co2:
  x: 360
  y: 440
molecules_other_utilisation_co2:
  x: 360
  y: 680
molecules_production_synthetic_kerosene_co2:
  x: 360
  y: 520
molecules_production_synthetic_methanol_co2:
  x: 360
  y: 600
molecules_production_synthetic_methanol_emitted_co2:
  x: 40
  y: 640
molecules_production_synthetic_methanol_utilised_co2:
  x: 40
  y: 560
molecules_transport_pipelines_co2:
  x: 1140
  y: 380
molecules_transport_ships_co2:
  x: 1140
  y: 480
