---
households_final_demand_electricity:
  demand: 190.184832
households_final_demand_network_gas:
  demand: 716.667408
households_final_demand_wood_pellets:
  demand: 26.0
households_final_demand_coal:
  demand: 0.0
households_final_demand_crude_oil:
  demand: 0.0
households_solar_pv_solar_radiation:
  demand: 39.0494117647059
households_collective_chp_network_gas:
  demand: 53.4468085106383
households_collective_chp_biogas:
  demand: 0.0
households_collective_chp_wood_pellets:
  demand: 0.0
households_collective_geothermal:
  demand: 0.0
households_final_demand_steam_hot_water:
  demand: 25.12
households_final_demand_for_space_heating_electricity-households_space_heater_electricity@electricity:
  parent_share: 0.9124
households_final_demand_for_space_heating_electricity-households_space_heater_heatpump_air_water_electricity@electricity:
  parent_share: 0.0425
households_final_demand_for_space_heating_electricity-households_space_heater_hybrid_heatpump_air_water_electricity@electricity:
  parent_share: 0.0
households_final_demand_for_space_heating_network_gas-households_space_heater_combined_network_gas@network_gas:
  parent_share: 0.9581
households_final_demand_for_space_heating_network_gas-households_space_heater_hybrid_heatpump_air_water_electricity@network_gas:
  parent_share: 0.0
households_final_demand_for_space_heating_network_gas-households_space_heater_network_gas@network_gas:
  parent_share: 0.0419
households_final_demand_for_hot_water_electricity-households_water_heater_heatpump_air_water_electricity@electricity:
  parent_share: 0.0133
households_final_demand_for_hot_water_electricity-households_water_heater_hybrid_heatpump_air_water_electricity@electricity:
  parent_share: 0.0
households_final_demand_for_hot_water_network_gas-households_water_heater_combined_network_gas@network_gas:
  parent_share: 0.9581
households_final_demand_for_hot_water_network_gas-households_water_heater_hybrid_heatpump_air_water_electricity@network_gas:
  parent_share: 0.0
buildings_local_production_electricity:
  demand: 370.13185877238
buildings_local_production_electricity-industry_final_demand_for_other_ict_electricity@electricity:
  parent_share: 0.018820319934372
buildings_local_production_electricity-buildings_final_demand_electricity@electricity:
  parent_share: 0.981179680065628
buildings_final_demand_network_gas:
  demand: 393.9792
buildings_final_demand_wood_pellets:
  demand: 0.0
buildings_final_demand_coal:
  demand: 0.0
buildings_final_demand_crude_oil:
  demand: 0.0
buildings_solar_pv_solar_radiation:
  demand: 19.5247058823529
buildings_collective_chp_network_gas:
  demand: 0.0
buildings_chp_engine_biogas:
  demand: 0.0
buildings_collective_chp_wood_pellets:
  demand: 0.0
buildings_collective_geothermal:
  demand: 0.0
buildings_final_demand_steam_hot_water:
  demand: 0.0
transport_useful_demand_cars:
  number_of_units: 12660.0
transport_useful_demand_bicycles:
  demand: 60.0
transport_final_demand_lpg:
  demand: 8.0461400065379
transport_final_demand_gasoline:
  demand: 215.685760024837
transport_final_demand_gasoline-transport_final_demand_for_road_gasoline@gasoline:
  parent_share: 1.0
transport_final_demand_diesel:
  demand: 198.408028331825
transport_final_demand_diesel-transport_final_demand_for_rail_diesel@diesel:
  parent_share: 0.0
transport_final_demand_diesel-transport_final_demand_for_road_diesel@diesel:
  parent_share: 0.894157508763311
transport_final_demand_compressed_network_gas:
  demand: 0.0
transport_final_demand_for_road_compressed_network_gas:
  demand: 0.0
transport_final_demand_lng:
  demand: 0.0
transport_final_demand_for_road_lng:
  demand: 0.0
transport_final_demand_for_shipping_lng:
  demand: 0.0
transport_final_demand_for_shipping_bio_lng:
  demand: 0.0
transport_final_demand_for_road_bio_lng:
  demand: 0.0
transport_final_demand_bio_lng:
  demand: 0.0
transport_final_demand_kerosene:
  demand: 0.0
transport_final_demand_heavy_fuel_oil:
  demand: 0.0
transport_final_demand_biodiesel:
  demand: 5.75266784452296
transport_final_demand_bio_ethanol:
  demand: 5.24733215547704
transport_final_demand_electricity:
  demand: 12.59854122762
transport_final_demand_for_rail_electricity-transport_tram_using_electricity@electricity:
  parent_share: 0.0
transport_final_demand_crude_oil_non_energetic:
  demand: 0.0
transport_final_demand_coal:
  demand: 0.0
agriculture_final_demand_electricity:
  demand: 17.9604
agriculture_chp_engine_network_gas:
  demand: 0.0
agriculture_final_demand_network_gas:
  demand: 48.8676
agriculture_final_demand_crude_oil:
  demand: 0.0
agriculture_final_demand_wood_pellets:
  demand: 0.0
agriculture_chp_engine_biogas:
  demand: 0.0
agriculture_chp_supercritical_wood_pellets:
  demand: 0.0
agriculture_final_demand_electricity-agriculture_heatpump_water_water_ts_electricity@electricity:
  parent_share: 0.0
agriculture_final_demand_electricity-agriculture_geothermal@electricity:
  parent_share: 0.0
agriculture_final_demand_steam_hot_water:
  demand: 0.0
other_final_demand_coal:
  demand: 0.0
other_final_demand_crude_oil:
  demand: 0.0
other_final_demand_electricity:
  demand: 0.0
other_final_demand_network_gas:
  demand: 0.0
other_final_demand_steam_hot_water:
  demand: 0.0
other_final_demand_wood_pellets:
  demand: 0.0
energy_cokesoven_consumption_coal_gas:
  demand: 0.0
energy_steel_hisarna_transformation_coal:
  demand: 0.0
energy_steel_blastfurnace_current_transformation_cokes:
  demand: 0.0
industry_final_demand_for_metal_network_gas-industry_steel_blastfurnace_burner_coal_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_metal_network_gas-industry_steel_electricfurnace_burner_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_metal_steam_hot_water-industry_steel_hisarna_consumption_useable_heat@useable_heat:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_steel_blastfurnace_bat_consumption_useable_heat@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_steel_blastfurnace_current_consumption_useable_heat@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_steel_electricfurnace_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_steel_hisarna_consumption_useable_heat@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_coal-industry_steel_blastfurnace_burner_coal_gas@coal:
  parent_share: 0.0
industry_final_demand_for_metal_network_gas-industry_aluminium_burner_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_aluminium_electrolysis_current_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_aluminium_electrolysis_bat_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_electricity-industry_aluminium_carbothermalreduction_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_metal_coal-industry_other_metals_burner_network_gas@coal:
  parent_share: 1.0
industry_final_demand_for_chemical_coal-industry_final_demand_for_chemical_refineries_coal@coal:
  parent_share: 0.0
energy_export_oil_products:
  demand: 0.0
? industry_final_demand_for_chemical_wood_pellets_non_energetic-industry_final_demand_for_chemical_refineries_wood_pellets_non_energetic@wood_pellets
: parent_share: 0.0
industry_final_demand_for_chemical_wood_pellets-industry_final_demand_for_chemical_refineries_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_for_chemical_steam_hot_water-industry_final_demand_for_chemical_refineries_steam_hot_water@steam_hot_water:
  parent_share: 0.0
? industry_final_demand_for_chemical_network_gas_non_energetic-industry_final_demand_for_chemical_refineries_network_gas_non_energetic@network_gas
: parent_share: 0.0
industry_final_demand_for_chemical_network_gas-industry_final_demand_for_chemical_refineries_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_chemical_electricity-industry_final_demand_for_chemical_refineries_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_refineries_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_chemical_coal_non_energetic-industry_final_demand_for_chemical_refineries_coal_non_energetic@coal:
  parent_share: 0.0
industry_final_demand_for_chemical_coal_non_energetic-industry_final_demand_for_chemical_fertilizers_coal_non_energetic@coal:
  parent_share: 0.0
industry_final_demand_for_chemical_coal-industry_final_demand_for_chemical_fertilizers_coal@coal:
  parent_share: 0.0
industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_fertilizers_crude_oil@crude_oil:
  parent_share: 0.0
? industry_final_demand_for_chemical_crude_oil_non_energetic-industry_final_demand_for_chemical_fertilizers_crude_oil_non_energetic@crude_oil
: parent_share: 0.0
industry_final_demand_for_chemical_electricity-industry_final_demand_for_chemical_fertilizers_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_chemical_network_gas-industry_final_demand_for_chemical_fertilizers_network_gas@network_gas:
  parent_share: 0.0
? industry_final_demand_for_chemical_network_gas_non_energetic-industry_final_demand_for_chemical_fertilizers_network_gas_non_energetic@network_gas
: parent_share: 0.0
? industry_final_demand_for_chemical_steam_hot_water-industry_final_demand_for_chemical_fertilizers_steam_hot_water@steam_hot_water
: parent_share: 0.0
industry_final_demand_for_chemical_wood_pellets-industry_final_demand_for_chemical_fertilizers_wood_pellets@wood_pellets:
  parent_share: 0.0
? industry_final_demand_for_chemical_wood_pellets_non_energetic-industry_final_demand_for_chemical_fertilizers_wood_pellets_non_energetic@wood_pellets
: parent_share: 0.0
industry_final_demand_for_chemical_other_crude_oil_non_energetic:
  demand: 0.0
? industry_final_demand_for_chemical_wood_pellets_non_energetic-industry_final_demand_for_chemical_other_wood_pellets_non_energetic@wood_pellets
: parent_share: 1.0
industry_final_demand_for_chemical_wood_pellets-industry_final_demand_for_chemical_other_wood_pellets@wood_pellets:
  parent_share: 1.0
industry_final_demand_for_chemical_steam_hot_water-industry_final_demand_for_chemical_other_steam_hot_water@steam_hot_water:
  parent_share: 1.0
? industry_final_demand_for_chemical_network_gas_non_energetic-industry_final_demand_for_chemical_other_network_gas_non_energetic@network_gas
: parent_share: 1.0
industry_final_demand_for_chemical_network_gas-industry_final_demand_for_chemical_other_network_gas@network_gas:
  parent_share: 1.0
industry_final_demand_for_chemical_electricity-industry_final_demand_for_chemical_other_electricity@electricity:
  parent_share: 1.0
industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_other_crude_oil@crude_oil:
  parent_share: 1.0
industry_final_demand_for_chemical_coal_non_energetic-industry_final_demand_for_chemical_other_coal_non_energetic@coal:
  parent_share: 1.0
industry_final_demand_for_chemical_coal-industry_final_demand_for_chemical_other_coal@coal:
  parent_share: 1.0
industry_final_demand_for_other_crude_oil_non_energetic:
  demand: 0.0
industry_final_demand_coal:
  demand: 0.0
industry_final_demand_coal-industry_final_demand_for_chemical_coal@coal:
  parent_share: 0.0
industry_final_demand_coal-industry_final_demand_for_metal_coal@coal:
  parent_share: 0.0
industry_final_demand_coal-industry_final_demand_for_other_coal@coal:
  parent_share: 1.0
industry_final_demand_for_other_coal-industry_final_demand_for_other_food_coal@coal:
  parent_share: 0.0
industry_final_demand_for_other_coal-industry_final_demand_for_other_paper_coal@coal:
  parent_share: 0.0
industry_final_demand_coal_non_energetic:
  demand: 0.0
industry_final_demand_coal_non_energetic-industry_final_demand_for_chemical_coal_non_energetic@coal:
  parent_share: 0.0
industry_final_demand_crude_oil:
  demand: 0.0
industry_final_demand_crude_oil-industry_final_demand_for_chemical_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_crude_oil-industry_final_demand_for_metal_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_crude_oil-industry_final_demand_for_other_crude_oil@crude_oil:
  parent_share: 1.0
industry_final_demand_for_other_crude_oil-industry_final_demand_for_other_food_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_for_other_crude_oil-industry_final_demand_for_other_paper_crude_oil@crude_oil:
  parent_share: 0.0
industry_final_demand_electricity:
  demand: 69.8148
industry_final_demand_electricity-industry_final_demand_for_metal_electricity@electricity:
  parent_share: 0.0
industry_final_demand_electricity-industry_final_demand_for_chemical_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_other_electricity-industry_final_demand_for_other_food_electricity@electricity:
  parent_share: 0.0
industry_final_demand_for_other_electricity-industry_final_demand_for_other_paper_electricity@electricity:
  parent_share: 1.0
industry_final_demand_network_gas:
  demand: 34.182
industry_final_demand_network_gas-industry_final_demand_for_metal_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_network_gas-industry_final_demand_for_chemical_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_other_network_gas-industry_final_demand_for_other_food_network_gas@network_gas:
  parent_share: 0.0
industry_final_demand_for_other_network_gas-industry_final_demand_for_other_paper_network_gas@network_gas:
  parent_share: 1.0
industry_final_demand_network_gas_non_energetic:
  demand: 0.0
industry_final_demand_steam_hot_water:
  demand: 0.0
industry_final_demand_steam_hot_water-industry_final_demand_for_metal_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_steam_hot_water-industry_final_demand_for_chemical_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_other_steam_hot_water-industry_final_demand_for_other_food_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_for_other_steam_hot_water-industry_final_demand_for_other_paper_steam_hot_water@steam_hot_water:
  parent_share: 0.0
industry_final_demand_wood_pellets:
  demand: 0.0
industry_final_demand_wood_pellets-industry_final_demand_for_metal_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_wood_pellets-industry_final_demand_for_chemical_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_for_other_wood_pellets-industry_final_demand_for_other_food_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_for_other_wood_pellets-industry_final_demand_for_other_paper_wood_pellets@wood_pellets:
  parent_share: 0.0
industry_final_demand_wood_pellets_non_energetic:
  demand: 0.0
industry_final_demand_wood_pellets_non_energetic-industry_final_demand_for_chemical_wood_pellets_non_energetic@wood_pellets:
  parent_share: 0.0
industry_final_demand_crude_oil_non_energetic-industry_final_demand_for_chemical_crude_oil_non_energetic@crude_oil:
  parent_share: 0.0
industry_final_demand_crude_oil_non_energetic-industry_final_demand_for_other_crude_oil_non_energetic@crude_oil:
  parent_share: 1.0
industry_chp_combined_cycle_gas_power_fuelmix:
  demand: 0.0
industry_chp_engine_gas_power_fuelmix:
  demand: 0.0
industry_chp_turbine_gas_power_fuelmix:
  demand: 0.0
industry_chp_ultra_supercritical_coal:
  demand: 0.0
energy_chp_supercritical_waste_mix:
  demand: 0.0
energy_heater_for_heat_network_wood_pellets:
  demand: 0.0
energy_heater_for_heat_network_network_gas:
  demand: 0.0
energy_heater_for_heat_network_waste_mix:
  demand: 0.0
energy_power_supercritical_waste_mix:
  demand: 0.0
energy_heat_network_loss:
  demand: 0.0
energy_heater_for_heat_network_geothermal:
  demand: 0.0
energy_heater_for_heat_network_crude_oil:
  demand: 0.0
energy_heater_for_heat_network_coal:
  demand: 0.0
energy_power_hydro_river:
  demand: 0.0
energy_power_sector_own_use_electricity:
  demand: 3.0
energy_power_solar_pv_solar_radiation:
  demand: 0.0
energy_power_wind_turbine_inland:
  demand: 0.0
energy_power_wind_turbine_coastal:
  demand: 0.0
energy_power_wind_turbine_offshore:
  demand: 0.0
energy_power_ultra_supercritical_network_gas:
  demand: 0.0
energy_power_ultra_supercritical_cofiring_coal:
  demand: 0.0
energy_power_ultra_supercritical_coal:
  demand: 0.0
energy_power_turbine_network_gas:
  demand: 0.0
energy_power_supercritical_coal:
  demand: 0.0
energy_power_nuclear_gen2_uranium_oxide:
  demand: 0.0
energy_chp_combined_cycle_network_gas:
  demand: 0.0
energy_power_engine_network_gas:
  demand: 0.0
energy_power_combined_cycle_network_gas:
  demand: 0.0
energy_power_combined_cycle_coal:
  demand: 0.0
energy_chp_ultra_supercritical_cofiring_coal:
  demand: 0.0
energy_chp_ultra_supercritical_coal:
  demand: 0.0
energy_extraction_uranium_oxide:
  demand: 0.0
energy_extraction_natural_gas:
  demand: 0.0
energy_extraction_crude_oil:
  demand: 0.0
energy_extraction_coal:
  demand: 0.0
energy_power_ultra_supercritical_crude_oil:
  demand: 0.0
energy_power_geothermal:
  demand: 0.0
energy_power_engine_diesel:
  demand: 0.0
energy_power_combined_cycle_ccs_network_gas:
  demand: 0.0
energy_power_combined_cycle_ccs_coal:
  demand: 0.0
buildings_collective_heatpump_water_water_electricity:
  demand: 0.0
households_collective_heatpump_water_water_electricity:
  demand: 0.0
industry_steel_blastfurnace_burner_coal_gas:
  input:
    network_gas: 1.0
    coal: 0.0
    coal_gas: 0.0
households_final_demand_solar_thermal:
  demand: 0.0
buildings_final_demand_solar_thermal:
  demand: 0.0
transport_final_demand_electricity-transport_final_demand_for_road_electricity@electricity:
  parent_share: 0.0
industry_other_metals_burner_network_gas:
  input:
    network_gas: 0.0
    coal: 1.0
    crude_oil: 0.0
other_final_demand_crude_oil_non_energetic:
  demand: 0.0
